version: '2'

networks:
   was9:
#     # driver: bridge
     external: true

services:

  wasnd_install_step1:
    image: was9_delete_me
    hostname: was
    build:
      context: ./install
      dockerfile: Dockerfile.v9.prereq
      args:
        user: wasadmin
        group: wasadmin
        URL: http://192.168.99.100:8080/WASND
        REPOS: http://192.168.99.100:8080/WASND/9000/BASE,http://192.168.99.100:8080/WASND/9007,http://192.168.99.100:8080/WASND/JDK-80511


  wasnd_install_step2:
    image: was9-noprofile
    hostname: dmgr
    build:
      context: ./install
      dockerfile: Dockerfile.v9.install
      args:
        WASVERSION: 9.0.0.7
        user: wasadmin
        group: wasadmin
    # depends_on:
    #   - wasnd_install_step1


  dmgr:
    image: wasnd9-dmgr
    container_name: dmgr
    hostname: dmgr
    build:
      context: ./dmgr
      dockerfile: Dockerfile.was9
      args:
        PROFILE_NAME: Dmgr01
        CELL_NAME: DefaultCell9
        NODE_NAME: ManagerNode01
        HOST_NAME: localhost
    environment:
      DUMMY: test
    hostname: dmgr
    expose:
      - "9060"
      - "9043"
      - "9809"
      - "8879"
      - "9632"
      - "9401"
      - "9403"
      - "9402"
      - "9100"
      - "7277"
      - "9352"
      - "5555"
      - "7060"
      - "11005"
      - "11006"
      - "9420"
    ports:
      - "9060:9060"
      - "9043:9043"
    volumes:
      - $PRJ_ROOT/wasconfig:/wasconfig:rw
    networks:
      - was9

  node01:
    image: wasnd9-node01
    container_name: node01
    hostname: node01
    build:
      context: ./custom
      dockerfile: Dockerfile.was9
      # args:
      #   PROFILE_NAME: Custom
      #   CELL_NAME: Dummy
      #   NODE_NAME: CustomNode
      #   HOST_NAME: localhost
    # depends_on:
    #   - dmgr
    environment:
      NODE_NAME: CustomNode01
      DMGR_HOST: dmgr
      DMGR_PORT: "8879"
    expose:
      - 2809
      - 9402
      - 9403
      - 9353
      - 9633
      - 9100
      - 11004
      - 11003
      - 9401
      - 7276
      - 7286
      - 5558
      - 5578
      - 5060
      - 5061
      - 8880
      - 9060
      - 9043
      - 9080
      - 9443
    networks:
     - was9

  node02:
    image: wasnd9-node02
    container_name: node02
    hostname: node02
    build:
      context: ./custom
      dockerfile: Dockerfile.was9
      # args:
      #   PROFILE_NAME: Custom
      #   CELL_NAME: Dummy
      #   NODE_NAME: CustomNode
      #   HOST_NAME: localhost
    # depends_on:
    #   - dmgr
    environment:
      NODE_NAME: CustomNode02
      DMGR_HOST: dmgr
      DMGR_PORT: "8879"
    expose:
      - 2809
      - 9402
      - 9403
      - 9353
      - 9633
      - 9100
      - 11004
      - 11003
      - 9401
      - 7276
      - 7286
      - 5558
      - 5578
      - 5060
      - 5061
      - 8880
      - 9060
      - 9043
      - 9080
      - 9443
    networks:
      - was9
