# Docker Compose YAML file for lighttpd

# build with:
# $ sudo docker-compose build

# start with:
# $ sudo docker-compose up

# after start, enter shell with:
# $ sudo docker exec -it lighttpddocker_lighttpd_1 ash

lighttpd:
    image: sebp/lighttpd
    container_name: httpd

# you need to mount the WAS855 Install directory to /WASINSTALL inside your virtualbox image!
    volumes:
        - /WASINSTALL:/var/www/localhost/htdocs

    ports:
        - "8080:80" # for testing purposes, (un)comment as required