version: '2'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #  URL: http://192.168.99.100:8080/
    image: opensuse
    container_name: tomcat
    hostname: tomcat
    environment:
      TEST : 'true'
    expose:
      - "8080"
      - "9080"
    ports:
      - "9080:9080"
      - "8080:8080"
    volumes:
      - ./volumes/default:/shared:rw
      - /c/Users/ThomasHikade/Documents/GitHub/ansible/src/ansible:/ansible-shared:rw

  demobox:
    build:
      context: .
      dockerfile: Dockerfile.demobox
      # args:
      #  URL: http://192.168.99.100:8080/
    image: demobox:latest
    container_name: demobox
    hostname: demobox
    environment:
      TEST : 'true'
    expose:
      - "8080"
    ports:
      - "8081:8080"
    #volumes:
